# Generated by Django 5.1.6 on 2025-03-03 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesistopic',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='thesistopic',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='thesistopic',
            name='created_by_student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thesis_topic', to='profiles.studentprofile'),
        ),
        migrations.AddField(
            model_name='thesistopic',
            name='created_by_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.supervisorprofile'),
        ),
        migrations.RemoveField(
            model_name='thesistopic',
            name='required_skills',
        ),
        migrations.AddField(
            model_name='thesistopic',
            name='required_skills',
            field=models.ManyToManyField(related_name='thesis_topics', to='profiles.skill'),
        ),
    ]
